from PyQt5 import QtCore, QtWidgets


class WindowKeyboard(object):
    def __init__(self):
        pass


    def setupUi(self, KeyboardSimulator):
        KeyboardSimulator.setObjectName("KeyboardSimulator")
        KeyboardSimulator.setEnabled(True)
        KeyboardSimulator.resize(1024, 768)
        KeyboardSimulator.setMinimumSize(QtCore.QSize(1024, 768))
        KeyboardSimulator.setMaximumSize(QtCore.QSize(1024, 768))
        KeyboardSimulator.setBaseSize(QtCore.QSize(1024, 768))
        KeyboardSimulator.setAutoFillBackground(False)
        KeyboardSimulator.setSizeGripEnabled(False)
        KeyboardSimulator.setModal(False)
        self.pushButton = QtWidgets.QPushButton(KeyboardSimulator)
        self.pushButton.setEnabled(True)
        self.pushButton.setGeometry(QtCore.QRect(170, 410, 50, 50))
        self.pushButton.setMouseTracking(False)
        self.pushButton.setTabletTracking(False)
        self.pushButton.setAcceptDrops(False)
        self.pushButton.setToolTip("")
        self.pushButton.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton.setAutoDefault(True)
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(KeyboardSimulator)
        self.pushButton_2.setEnabled(True)
        self.pushButton_2.setGeometry(QtCore.QRect(230, 410, 50, 50))
        self.pushButton_2.setMouseTracking(False)
        self.pushButton_2.setTabletTracking(False)
        self.pushButton_2.setAcceptDrops(False)
        self.pushButton_2.setToolTip("")
        self.pushButton_2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_2.setAutoDefault(True)
        self.pushButton_2.setDefault(False)
        self.pushButton_2.setFlat(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(KeyboardSimulator)
        self.pushButton_3.setEnabled(True)
        self.pushButton_3.setGeometry(QtCore.QRect(350, 410, 50, 50))
        self.pushButton_3.setMouseTracking(False)
        self.pushButton_3.setTabletTracking(False)
        self.pushButton_3.setAcceptDrops(False)
        self.pushButton_3.setToolTip("")
        self.pushButton_3.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_3.setAutoDefault(True)
        self.pushButton_3.setDefault(False)
        self.pushButton_3.setFlat(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(KeyboardSimulator)
        self.pushButton_4.setEnabled(True)
        self.pushButton_4.setGeometry(QtCore.QRect(290, 410, 50, 50))
        self.pushButton_4.setMouseTracking(False)
        self.pushButton_4.setTabletTracking(False)
        self.pushButton_4.setAcceptDrops(False)
        self.pushButton_4.setToolTip("")
        self.pushButton_4.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_4.setAutoDefault(True)
        self.pushButton_4.setDefault(False)
        self.pushButton_4.setFlat(False)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(KeyboardSimulator)
        self.pushButton_5.setEnabled(True)
        self.pushButton_5.setGeometry(QtCore.QRect(470, 410, 50, 50))
        self.pushButton_5.setMouseTracking(False)
        self.pushButton_5.setTabletTracking(False)
        self.pushButton_5.setAcceptDrops(False)
        self.pushButton_5.setToolTip("")
        self.pushButton_5.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_5.setAutoDefault(True)
        self.pushButton_5.setDefault(False)
        self.pushButton_5.setFlat(False)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(KeyboardSimulator)
        self.pushButton_6.setEnabled(True)
        self.pushButton_6.setGeometry(QtCore.QRect(530, 410, 50, 50))
        self.pushButton_6.setMouseTracking(False)
        self.pushButton_6.setTabletTracking(False)
        self.pushButton_6.setAcceptDrops(False)
        self.pushButton_6.setToolTip("")
        self.pushButton_6.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_6.setAutoDefault(True)
        self.pushButton_6.setDefault(False)
        self.pushButton_6.setFlat(False)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(KeyboardSimulator)
        self.pushButton_7.setEnabled(True)
        self.pushButton_7.setGeometry(QtCore.QRect(410, 410, 50, 50))
        self.pushButton_7.setMouseTracking(False)
        self.pushButton_7.setTabletTracking(False)
        self.pushButton_7.setAcceptDrops(False)
        self.pushButton_7.setToolTip("")
        self.pushButton_7.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_7.setAutoDefault(True)
        self.pushButton_7.setDefault(False)
        self.pushButton_7.setFlat(False)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(KeyboardSimulator)
        self.pushButton_8.setEnabled(True)
        self.pushButton_8.setGeometry(QtCore.QRect(590, 410, 50, 50))
        self.pushButton_8.setMouseTracking(False)
        self.pushButton_8.setTabletTracking(False)
        self.pushButton_8.setAcceptDrops(False)
        self.pushButton_8.setToolTip("")
        self.pushButton_8.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_8.setAutoDefault(True)
        self.pushButton_8.setDefault(False)
        self.pushButton_8.setFlat(False)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(KeyboardSimulator)
        self.pushButton_9.setEnabled(True)
        self.pushButton_9.setGeometry(QtCore.QRect(770, 410, 50, 50))
        self.pushButton_9.setMouseTracking(False)
        self.pushButton_9.setTabletTracking(False)
        self.pushButton_9.setAcceptDrops(False)
        self.pushButton_9.setToolTip("")
        self.pushButton_9.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_9.setAutoDefault(True)
        self.pushButton_9.setDefault(False)
        self.pushButton_9.setFlat(False)
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(KeyboardSimulator)
        self.pushButton_10.setEnabled(True)
        self.pushButton_10.setGeometry(QtCore.QRect(710, 410, 50, 50))
        self.pushButton_10.setMouseTracking(False)
        self.pushButton_10.setTabletTracking(False)
        self.pushButton_10.setAcceptDrops(False)
        self.pushButton_10.setToolTip("")
        self.pushButton_10.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_10.setAutoDefault(True)
        self.pushButton_10.setDefault(False)
        self.pushButton_10.setFlat(False)
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(KeyboardSimulator)
        self.pushButton_11.setEnabled(True)
        self.pushButton_11.setGeometry(QtCore.QRect(650, 409, 50, 51))
        self.pushButton_11.setMouseTracking(False)
        self.pushButton_11.setTabletTracking(False)
        self.pushButton_11.setAcceptDrops(False)
        self.pushButton_11.setToolTip("")
        self.pushButton_11.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_11.setAutoDefault(True)
        self.pushButton_11.setDefault(False)
        self.pushButton_11.setFlat(False)
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(KeyboardSimulator)
        self.pushButton_12.setEnabled(True)
        self.pushButton_12.setGeometry(QtCore.QRect(830, 410, 50, 50))
        self.pushButton_12.setMouseTracking(False)
        self.pushButton_12.setTabletTracking(False)
        self.pushButton_12.setAcceptDrops(False)
        self.pushButton_12.setToolTip("")
        self.pushButton_12.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_12.setAutoDefault(True)
        self.pushButton_12.setDefault(False)
        self.pushButton_12.setFlat(False)
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_14 = QtWidgets.QPushButton(KeyboardSimulator)
        self.pushButton_14.setEnabled(True)
        self.pushButton_14.setGeometry(QtCore.QRect(730, 470, 50, 50))
        self.pushButton_14.setMouseTracking(False)
        self.pushButton_14.setTabletTracking(False)
        self.pushButton_14.setAcceptDrops(False)
        self.pushButton_14.setToolTip("")
        self.pushButton_14.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_14.setAutoDefault(True)
        self.pushButton_14.setDefault(False)
        self.pushButton_14.setFlat(False)
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(KeyboardSimulator)
        self.pushButton_15.setEnabled(True)
        self.pushButton_15.setGeometry(QtCore.QRect(250, 470, 50, 50))
        self.pushButton_15.setMouseTracking(False)
        self.pushButton_15.setTabletTracking(False)
        self.pushButton_15.setAcceptDrops(False)
        self.pushButton_15.setToolTip("")
        self.pushButton_15.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_15.setAutoDefault(True)
        self.pushButton_15.setDefault(False)
        self.pushButton_15.setFlat(False)
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(KeyboardSimulator)
        self.pushButton_16.setEnabled(True)
        self.pushButton_16.setGeometry(QtCore.QRect(310, 470, 50, 50))
        self.pushButton_16.setMouseTracking(False)
        self.pushButton_16.setTabletTracking(False)
        self.pushButton_16.setAcceptDrops(False)
        self.pushButton_16.setToolTip("")
        self.pushButton_16.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_16.setAutoDefault(True)
        self.pushButton_16.setDefault(False)
        self.pushButton_16.setFlat(False)
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(KeyboardSimulator)
        self.pushButton_17.setEnabled(True)
        self.pushButton_17.setGeometry(QtCore.QRect(550, 470, 50, 50))
        self.pushButton_17.setMouseTracking(False)
        self.pushButton_17.setTabletTracking(False)
        self.pushButton_17.setAcceptDrops(False)
        self.pushButton_17.setToolTip("")
        self.pushButton_17.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_17.setAutoDefault(True)
        self.pushButton_17.setDefault(False)
        self.pushButton_17.setFlat(False)
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(KeyboardSimulator)
        self.pushButton_18.setEnabled(True)
        self.pushButton_18.setGeometry(QtCore.QRect(490, 470, 50, 50))
        self.pushButton_18.setMouseTracking(False)
        self.pushButton_18.setTabletTracking(False)
        self.pushButton_18.setAcceptDrops(False)
        self.pushButton_18.setToolTip("")
        self.pushButton_18.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_18.setAutoDefault(True)
        self.pushButton_18.setDefault(False)
        self.pushButton_18.setFlat(False)
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(KeyboardSimulator)
        self.pushButton_19.setEnabled(True)
        self.pushButton_19.setGeometry(QtCore.QRect(670, 469, 50, 51))
        self.pushButton_19.setMouseTracking(False)
        self.pushButton_19.setTabletTracking(False)
        self.pushButton_19.setAcceptDrops(False)
        self.pushButton_19.setToolTip("")
        self.pushButton_19.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_19.setAutoDefault(True)
        self.pushButton_19.setDefault(False)
        self.pushButton_19.setFlat(False)
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(KeyboardSimulator)
        self.pushButton_20.setEnabled(True)
        self.pushButton_20.setGeometry(QtCore.QRect(430, 470, 50, 50))
        self.pushButton_20.setMouseTracking(False)
        self.pushButton_20.setTabletTracking(False)
        self.pushButton_20.setAcceptDrops(False)
        self.pushButton_20.setToolTip("")
        self.pushButton_20.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_20.setAutoDefault(True)
        self.pushButton_20.setDefault(False)
        self.pushButton_20.setFlat(False)
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(KeyboardSimulator)
        self.pushButton_21.setEnabled(True)
        self.pushButton_21.setGeometry(QtCore.QRect(790, 470, 50, 50))
        self.pushButton_21.setMouseTracking(False)
        self.pushButton_21.setTabletTracking(False)
        self.pushButton_21.setAcceptDrops(False)
        self.pushButton_21.setToolTip("")
        self.pushButton_21.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_21.setAutoDefault(True)
        self.pushButton_21.setDefault(False)
        self.pushButton_21.setFlat(False)
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(KeyboardSimulator)
        self.pushButton_22.setEnabled(True)
        self.pushButton_22.setGeometry(QtCore.QRect(610, 470, 50, 50))
        self.pushButton_22.setMouseTracking(False)
        self.pushButton_22.setTabletTracking(False)
        self.pushButton_22.setAcceptDrops(False)
        self.pushButton_22.setToolTip("")
        self.pushButton_22.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_22.setAutoDefault(True)
        self.pushButton_22.setDefault(False)
        self.pushButton_22.setFlat(False)
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_23 = QtWidgets.QPushButton(KeyboardSimulator)
        self.pushButton_23.setEnabled(True)
        self.pushButton_23.setGeometry(QtCore.QRect(190, 470, 50, 50))
        self.pushButton_23.setMouseTracking(False)
        self.pushButton_23.setTabletTracking(False)
        self.pushButton_23.setAcceptDrops(False)
        self.pushButton_23.setToolTip("")
        self.pushButton_23.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_23.setAutoDefault(True)
        self.pushButton_23.setDefault(False)
        self.pushButton_23.setFlat(False)
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_24 = QtWidgets.QPushButton(KeyboardSimulator)
        self.pushButton_24.setEnabled(True)
        self.pushButton_24.setGeometry(QtCore.QRect(370, 470, 50, 50))
        self.pushButton_24.setMouseTracking(False)
        self.pushButton_24.setTabletTracking(False)
        self.pushButton_24.setAcceptDrops(False)
        self.pushButton_24.setToolTip("")
        self.pushButton_24.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_24.setAutoDefault(True)
        self.pushButton_24.setDefault(False)
        self.pushButton_24.setFlat(False)
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_25 = QtWidgets.QPushButton(KeyboardSimulator)
        self.pushButton_25.setEnabled(True)
        self.pushButton_25.setGeometry(QtCore.QRect(580, 530, 50, 50))
        self.pushButton_25.setMouseTracking(False)
        self.pushButton_25.setTabletTracking(False)
        self.pushButton_25.setAcceptDrops(False)
        self.pushButton_25.setToolTip("")
        self.pushButton_25.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_25.setAutoDefault(True)
        self.pushButton_25.setDefault(False)
        self.pushButton_25.setFlat(False)
        self.pushButton_25.setObjectName("pushButton_25")
        self.pushButton_27 = QtWidgets.QPushButton(KeyboardSimulator)
        self.pushButton_27.setEnabled(True)
        self.pushButton_27.setGeometry(QtCore.QRect(280, 530, 50, 50))
        self.pushButton_27.setMouseTracking(False)
        self.pushButton_27.setTabletTracking(False)
        self.pushButton_27.setAcceptDrops(False)
        self.pushButton_27.setToolTip("")
        self.pushButton_27.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_27.setAutoDefault(True)
        self.pushButton_27.setDefault(False)
        self.pushButton_27.setFlat(False)
        self.pushButton_27.setObjectName("pushButton_27")
        self.pushButton_28 = QtWidgets.QPushButton(KeyboardSimulator)
        self.pushButton_28.setEnabled(True)
        self.pushButton_28.setGeometry(QtCore.QRect(700, 529, 50, 51))
        self.pushButton_28.setMouseTracking(False)
        self.pushButton_28.setTabletTracking(False)
        self.pushButton_28.setAcceptDrops(False)
        self.pushButton_28.setToolTip("")
        self.pushButton_28.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_28.setAutoDefault(True)
        self.pushButton_28.setDefault(False)
        self.pushButton_28.setFlat(False)
        self.pushButton_28.setObjectName("pushButton_28")
        self.pushButton_29 = QtWidgets.QPushButton(KeyboardSimulator)
        self.pushButton_29.setEnabled(True)
        self.pushButton_29.setGeometry(QtCore.QRect(760, 530, 50, 50))
        self.pushButton_29.setMouseTracking(False)
        self.pushButton_29.setTabletTracking(False)
        self.pushButton_29.setAcceptDrops(False)
        self.pushButton_29.setToolTip("")
        self.pushButton_29.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_29.setAutoDefault(True)
        self.pushButton_29.setDefault(False)
        self.pushButton_29.setFlat(False)
        self.pushButton_29.setObjectName("pushButton_29")
        self.pushButton_30 = QtWidgets.QPushButton(KeyboardSimulator)
        self.pushButton_30.setEnabled(True)
        self.pushButton_30.setGeometry(QtCore.QRect(640, 530, 50, 50))
        self.pushButton_30.setMouseTracking(False)
        self.pushButton_30.setTabletTracking(False)
        self.pushButton_30.setAcceptDrops(False)
        self.pushButton_30.setToolTip("")
        self.pushButton_30.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_30.setAutoDefault(True)
        self.pushButton_30.setDefault(False)
        self.pushButton_30.setFlat(False)
        self.pushButton_30.setObjectName("pushButton_30")
        self.pushButton_31 = QtWidgets.QPushButton(KeyboardSimulator)
        self.pushButton_31.setEnabled(True)
        self.pushButton_31.setGeometry(QtCore.QRect(520, 530, 50, 50))
        self.pushButton_31.setMouseTracking(False)
        self.pushButton_31.setTabletTracking(False)
        self.pushButton_31.setAcceptDrops(False)
        self.pushButton_31.setToolTip("")
        self.pushButton_31.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_31.setAutoDefault(True)
        self.pushButton_31.setDefault(False)
        self.pushButton_31.setFlat(False)
        self.pushButton_31.setObjectName("pushButton_31")
        self.pushButton_32 = QtWidgets.QPushButton(KeyboardSimulator)
        self.pushButton_32.setEnabled(True)
        self.pushButton_32.setGeometry(QtCore.QRect(340, 530, 50, 50))
        self.pushButton_32.setMouseTracking(False)
        self.pushButton_32.setTabletTracking(False)
        self.pushButton_32.setAcceptDrops(False)
        self.pushButton_32.setToolTip("")
        self.pushButton_32.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_32.setAutoDefault(True)
        self.pushButton_32.setDefault(False)
        self.pushButton_32.setFlat(False)
        self.pushButton_32.setObjectName("pushButton_32")
        self.pushButton_33 = QtWidgets.QPushButton(KeyboardSimulator)
        self.pushButton_33.setEnabled(True)
        self.pushButton_33.setGeometry(QtCore.QRect(460, 530, 50, 50))
        self.pushButton_33.setMouseTracking(False)
        self.pushButton_33.setTabletTracking(False)
        self.pushButton_33.setAcceptDrops(False)
        self.pushButton_33.setToolTip("")
        self.pushButton_33.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_33.setAutoDefault(True)
        self.pushButton_33.setDefault(False)
        self.pushButton_33.setFlat(False)
        self.pushButton_33.setObjectName("pushButton_33")
        self.pushButton_34 = QtWidgets.QPushButton(KeyboardSimulator)
        self.pushButton_34.setEnabled(True)
        self.pushButton_34.setGeometry(QtCore.QRect(220, 530, 50, 50))
        self.pushButton_34.setMouseTracking(False)
        self.pushButton_34.setTabletTracking(False)
        self.pushButton_34.setAcceptDrops(False)
        self.pushButton_34.setToolTip("")
        self.pushButton_34.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_34.setAutoDefault(True)
        self.pushButton_34.setDefault(False)
        self.pushButton_34.setFlat(False)
        self.pushButton_34.setObjectName("pushButton_34")
        self.pushButton_35 = QtWidgets.QPushButton(KeyboardSimulator)
        self.pushButton_35.setEnabled(True)
        self.pushButton_35.setGeometry(QtCore.QRect(400, 530, 50, 50))
        self.pushButton_35.setMouseTracking(False)
        self.pushButton_35.setTabletTracking(False)
        self.pushButton_35.setAcceptDrops(False)
        self.pushButton_35.setToolTip("")
        self.pushButton_35.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_35.setAutoDefault(True)
        self.pushButton_35.setDefault(False)
        self.pushButton_35.setFlat(False)
        self.pushButton_35.setObjectName("pushButton_35")
        self.pushButton_13 = QtWidgets.QPushButton(KeyboardSimulator)
        self.pushButton_13.setEnabled(True)
        self.pushButton_13.setGeometry(QtCore.QRect(890, 410, 50, 50))
        self.pushButton_13.setMouseTracking(False)
        self.pushButton_13.setTabletTracking(False)
        self.pushButton_13.setAcceptDrops(False)
        self.pushButton_13.setToolTip("")
        self.pushButton_13.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_13.setAutoDefault(True)
        self.pushButton_13.setDefault(False)
        self.pushButton_13.setFlat(False)
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_37 = QtWidgets.QPushButton(KeyboardSimulator)
        self.pushButton_37.setEnabled(True)
        self.pushButton_37.setGeometry(QtCore.QRect(850, 470, 91, 50))
        self.pushButton_37.setMouseTracking(False)
        self.pushButton_37.setTabletTracking(False)
        self.pushButton_37.setAcceptDrops(False)
        self.pushButton_37.setToolTip("")
        self.pushButton_37.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_37.setAutoDefault(True)
        self.pushButton_37.setDefault(False)
        self.pushButton_37.setFlat(False)
        self.pushButton_37.setObjectName("pushButton_37")
        self.pushButton_38 = QtWidgets.QPushButton(KeyboardSimulator)
        self.pushButton_38.setEnabled(True)
        self.pushButton_38.setGeometry(QtCore.QRect(90, 530, 121, 50))
        self.pushButton_38.setMouseTracking(False)
        self.pushButton_38.setTabletTracking(False)
        self.pushButton_38.setAcceptDrops(False)
        self.pushButton_38.setToolTip("")
        self.pushButton_38.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_38.setAutoDefault(True)
        self.pushButton_38.setDefault(False)
        self.pushButton_38.setFlat(False)
        self.pushButton_38.setObjectName("pushButton_38")
        self.pushButton_39 = QtWidgets.QPushButton(KeyboardSimulator)
        self.pushButton_39.setEnabled(True)
        self.pushButton_39.setGeometry(QtCore.QRect(90, 470, 91, 50))
        self.pushButton_39.setMouseTracking(False)
        self.pushButton_39.setTabletTracking(False)
        self.pushButton_39.setAcceptDrops(False)
        self.pushButton_39.setToolTip("")
        self.pushButton_39.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_39.setAutoDefault(True)
        self.pushButton_39.setDefault(False)
        self.pushButton_39.setFlat(False)
        self.pushButton_39.setObjectName("pushButton_39")
        self.pushButton_40 = QtWidgets.QPushButton(KeyboardSimulator)
        self.pushButton_40.setEnabled(True)
        self.pushButton_40.setGeometry(QtCore.QRect(90, 410, 71, 50))
        self.pushButton_40.setMouseTracking(False)
        self.pushButton_40.setTabletTracking(False)
        self.pushButton_40.setAcceptDrops(False)
        self.pushButton_40.setToolTip("")
        self.pushButton_40.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_40.setAutoDefault(True)
        self.pushButton_40.setDefault(False)
        self.pushButton_40.setFlat(False)
        self.pushButton_40.setObjectName("pushButton_40")
        self.pushButton_26 = QtWidgets.QPushButton(KeyboardSimulator)
        self.pushButton_26.setEnabled(True)
        self.pushButton_26.setGeometry(QtCore.QRect(690, 350, 50, 50))
        self.pushButton_26.setMouseTracking(False)
        self.pushButton_26.setTabletTracking(False)
        self.pushButton_26.setAcceptDrops(False)
        self.pushButton_26.setToolTip("")
        self.pushButton_26.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_26.setAutoDefault(True)
        self.pushButton_26.setDefault(False)
        self.pushButton_26.setFlat(False)
        self.pushButton_26.setObjectName("pushButton_26")
        self.pushButton_41 = QtWidgets.QPushButton(KeyboardSimulator)
        self.pushButton_41.setEnabled(True)
        self.pushButton_41.setGeometry(QtCore.QRect(210, 350, 50, 50))
        self.pushButton_41.setMouseTracking(False)
        self.pushButton_41.setTabletTracking(False)
        self.pushButton_41.setAcceptDrops(False)
        self.pushButton_41.setToolTip("")
        self.pushButton_41.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_41.setAutoDefault(True)
        self.pushButton_41.setDefault(False)
        self.pushButton_41.setFlat(False)
        self.pushButton_41.setObjectName("pushButton_41")
        self.pushButton_42 = QtWidgets.QPushButton(KeyboardSimulator)
        self.pushButton_42.setEnabled(True)
        self.pushButton_42.setGeometry(QtCore.QRect(270, 350, 50, 50))
        self.pushButton_42.setMouseTracking(False)
        self.pushButton_42.setTabletTracking(False)
        self.pushButton_42.setAcceptDrops(False)
        self.pushButton_42.setToolTip("")
        self.pushButton_42.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_42.setAutoDefault(True)
        self.pushButton_42.setDefault(False)
        self.pushButton_42.setFlat(False)
        self.pushButton_42.setObjectName("pushButton_42")
        self.pushButton_43 = QtWidgets.QPushButton(KeyboardSimulator)
        self.pushButton_43.setEnabled(True)
        self.pushButton_43.setGeometry(QtCore.QRect(510, 350, 50, 50))
        self.pushButton_43.setMouseTracking(False)
        self.pushButton_43.setTabletTracking(False)
        self.pushButton_43.setAcceptDrops(False)
        self.pushButton_43.setToolTip("")
        self.pushButton_43.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_43.setAutoDefault(True)
        self.pushButton_43.setDefault(False)
        self.pushButton_43.setFlat(False)
        self.pushButton_43.setObjectName("pushButton_43")
        self.pushButton_44 = QtWidgets.QPushButton(KeyboardSimulator)
        self.pushButton_44.setEnabled(True)
        self.pushButton_44.setGeometry(QtCore.QRect(450, 350, 50, 50))
        self.pushButton_44.setMouseTracking(False)
        self.pushButton_44.setTabletTracking(False)
        self.pushButton_44.setAcceptDrops(False)
        self.pushButton_44.setToolTip("")
        self.pushButton_44.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_44.setAutoDefault(True)
        self.pushButton_44.setDefault(False)
        self.pushButton_44.setFlat(False)
        self.pushButton_44.setObjectName("pushButton_44")
        self.pushButton_45 = QtWidgets.QPushButton(KeyboardSimulator)
        self.pushButton_45.setEnabled(True)
        self.pushButton_45.setGeometry(QtCore.QRect(630, 349, 50, 51))
        self.pushButton_45.setMouseTracking(False)
        self.pushButton_45.setTabletTracking(False)
        self.pushButton_45.setAcceptDrops(False)
        self.pushButton_45.setToolTip("")
        self.pushButton_45.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_45.setAutoDefault(True)
        self.pushButton_45.setDefault(False)
        self.pushButton_45.setFlat(False)
        self.pushButton_45.setObjectName("pushButton_45")
        self.pushButton_46 = QtWidgets.QPushButton(KeyboardSimulator)
        self.pushButton_46.setEnabled(True)
        self.pushButton_46.setGeometry(QtCore.QRect(390, 350, 50, 50))
        self.pushButton_46.setMouseTracking(False)
        self.pushButton_46.setTabletTracking(False)
        self.pushButton_46.setAcceptDrops(False)
        self.pushButton_46.setToolTip("")
        self.pushButton_46.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_46.setAutoDefault(True)
        self.pushButton_46.setDefault(False)
        self.pushButton_46.setFlat(False)
        self.pushButton_46.setObjectName("pushButton_46")
        self.pushButton_47 = QtWidgets.QPushButton(KeyboardSimulator)
        self.pushButton_47.setEnabled(True)
        self.pushButton_47.setGeometry(QtCore.QRect(570, 350, 50, 50))
        self.pushButton_47.setMouseTracking(False)
        self.pushButton_47.setTabletTracking(False)
        self.pushButton_47.setAcceptDrops(False)
        self.pushButton_47.setToolTip("")
        self.pushButton_47.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_47.setAutoDefault(True)
        self.pushButton_47.setDefault(False)
        self.pushButton_47.setFlat(False)
        self.pushButton_47.setObjectName("pushButton_47")
        self.pushButton_48 = QtWidgets.QPushButton(KeyboardSimulator)
        self.pushButton_48.setEnabled(True)
        self.pushButton_48.setGeometry(QtCore.QRect(150, 350, 50, 50))
        self.pushButton_48.setMouseTracking(False)
        self.pushButton_48.setTabletTracking(False)
        self.pushButton_48.setAcceptDrops(False)
        self.pushButton_48.setToolTip("")
        self.pushButton_48.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_48.setAutoDefault(True)
        self.pushButton_48.setDefault(False)
        self.pushButton_48.setFlat(False)
        self.pushButton_48.setObjectName("pushButton_48")
        self.pushButton_49 = QtWidgets.QPushButton(KeyboardSimulator)
        self.pushButton_49.setEnabled(True)
        self.pushButton_49.setGeometry(QtCore.QRect(330, 350, 50, 50))
        self.pushButton_49.setMouseTracking(False)
        self.pushButton_49.setTabletTracking(False)
        self.pushButton_49.setAcceptDrops(False)
        self.pushButton_49.setToolTip("")
        self.pushButton_49.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_49.setAutoDefault(True)
        self.pushButton_49.setDefault(False)
        self.pushButton_49.setFlat(False)
        self.pushButton_49.setObjectName("pushButton_49")
        self.pushButton_50 = QtWidgets.QPushButton(KeyboardSimulator)
        self.pushButton_50.setEnabled(True)
        self.pushButton_50.setGeometry(QtCore.QRect(750, 349, 50, 51))
        self.pushButton_50.setMouseTracking(False)
        self.pushButton_50.setTabletTracking(False)
        self.pushButton_50.setAcceptDrops(False)
        self.pushButton_50.setToolTip("")
        self.pushButton_50.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_50.setAutoDefault(True)
        self.pushButton_50.setDefault(False)
        self.pushButton_50.setFlat(False)
        self.pushButton_50.setObjectName("pushButton_50")
        self.pushButton_51 = QtWidgets.QPushButton(KeyboardSimulator)
        self.pushButton_51.setEnabled(True)
        self.pushButton_51.setGeometry(QtCore.QRect(810, 350, 50, 50))
        self.pushButton_51.setMouseTracking(False)
        self.pushButton_51.setTabletTracking(False)
        self.pushButton_51.setAcceptDrops(False)
        self.pushButton_51.setToolTip("")
        self.pushButton_51.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_51.setAutoDefault(True)
        self.pushButton_51.setDefault(False)
        self.pushButton_51.setFlat(False)
        self.pushButton_51.setObjectName("pushButton_51")
        self.pushButton_52 = QtWidgets.QPushButton(KeyboardSimulator)
        self.pushButton_52.setEnabled(True)
        self.pushButton_52.setGeometry(QtCore.QRect(90, 350, 50, 50))
        self.pushButton_52.setMouseTracking(False)
        self.pushButton_52.setTabletTracking(False)
        self.pushButton_52.setAcceptDrops(False)
        self.pushButton_52.setToolTip("")
        self.pushButton_52.setStyleSheet("QPushButtom {\n"
"border-radius: 10px;\n"
"}")
        self.pushButton_52.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_52.setAutoDefault(True)
        self.pushButton_52.setDefault(False)
        self.pushButton_52.setFlat(False)
        self.pushButton_52.setObjectName("pushButton_52")
        self.pushButton_53 = QtWidgets.QPushButton(KeyboardSimulator)
        self.pushButton_53.setEnabled(True)
        self.pushButton_53.setGeometry(QtCore.QRect(870, 350, 71, 50))
        self.pushButton_53.setMouseTracking(False)
        self.pushButton_53.setTabletTracking(False)
        self.pushButton_53.setAcceptDrops(False)
        self.pushButton_53.setToolTip("")
        self.pushButton_53.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_53.setAutoDefault(True)
        self.pushButton_53.setDefault(False)
        self.pushButton_53.setFlat(False)
        self.pushButton_53.setObjectName("pushButton_53")
        self.pushButton_54 = QtWidgets.QPushButton(KeyboardSimulator)
        self.pushButton_54.setEnabled(True)
        self.pushButton_54.setGeometry(QtCore.QRect(280, 590, 471, 50))
        self.pushButton_54.setMouseTracking(False)
        self.pushButton_54.setTabletTracking(False)
        self.pushButton_54.setAcceptDrops(False)
        self.pushButton_54.setToolTip("")
        self.pushButton_54.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_54.setText("")
        self.pushButton_54.setAutoDefault(True)
        self.pushButton_54.setDefault(False)
        self.pushButton_54.setFlat(False)
        self.pushButton_54.setObjectName("pushButton_54")
        self.pushButton_55 = QtWidgets.QPushButton(KeyboardSimulator)
        self.pushButton_55.setEnabled(True)
        self.pushButton_55.setGeometry(QtCore.QRect(820, 530, 121, 50))
        self.pushButton_55.setMouseTracking(False)
        self.pushButton_55.setTabletTracking(False)
        self.pushButton_55.setAcceptDrops(False)
        self.pushButton_55.setToolTip("")
        self.pushButton_55.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_55.setAutoDefault(True)
        self.pushButton_55.setDefault(False)
        self.pushButton_55.setFlat(False)
        self.pushButton_55.setObjectName("pushButton_55")
        self.lineEdit = QtWidgets.QLineEdit(KeyboardSimulator)
        self.lineEdit.setGeometry(QtCore.QRect(110, 250, 811, 91))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.progressBar = QtWidgets.QProgressBar(KeyboardSimulator)
        self.progressBar.setGeometry(QtCore.QRect(170, 160, 118, 23))
        self.progressBar.setProperty("value", 100)
        self.progressBar.setObjectName("progressBar")
        self.textBrowser = QtWidgets.QTextBrowser(KeyboardSimulator)
        self.textBrowser.setGeometry(QtCore.QRect(110, 201, 811, 41))
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(KeyboardSimulator)
        self.label.setGeometry(QtCore.QRect(170, 130, 111, 16))
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(KeyboardSimulator)
        self.line.setGeometry(QtCore.QRect(180, 150, 90, 3))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_2 = QtWidgets.QLabel(KeyboardSimulator)
        self.label_2.setGeometry(QtCore.QRect(320, 130, 90, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(KeyboardSimulator)
        self.label_3.setGeometry(QtCore.QRect(430, 130, 90, 20))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(KeyboardSimulator)
        self.label_4.setGeometry(QtCore.QRect(540, 130, 90, 20))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(KeyboardSimulator)
        self.label_5.setGeometry(QtCore.QRect(650, 130, 90, 20))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(KeyboardSimulator)
        self.label_6.setGeometry(QtCore.QRect(760, 130, 90, 20))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.line_2 = QtWidgets.QFrame(KeyboardSimulator)
        self.line_2.setGeometry(QtCore.QRect(330, 150, 510, 3))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_7 = QtWidgets.QLabel(KeyboardSimulator)
        self.label_7.setGeometry(QtCore.QRect(650, 160, 90, 20))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(KeyboardSimulator)
        self.label_8.setGeometry(QtCore.QRect(760, 160, 90, 20))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(KeyboardSimulator)
        self.label_9.setGeometry(QtCore.QRect(320, 160, 90, 20))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(KeyboardSimulator)
        self.label_10.setGeometry(QtCore.QRect(430, 160, 90, 20))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(KeyboardSimulator)
        self.label_11.setGeometry(QtCore.QRect(540, 160, 90, 20))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")

        self.retranslateUi(KeyboardSimulator)
        QtCore.QMetaObject.connectSlotsByName(KeyboardSimulator)

    def retranslateUi(self, KeyboardSimulator):
        _translate = QtCore.QCoreApplication.translate
        KeyboardSimulator.setWindowTitle(_translate("KeyboardSimulator", "Клавиатурный тренажёр"))
        self.pushButton.setText(_translate("KeyboardSimulator", "Й"))
        self.pushButton_2.setText(_translate("KeyboardSimulator", "Ц"))
        self.pushButton_3.setText(_translate("KeyboardSimulator", "К"))
        self.pushButton_4.setText(_translate("KeyboardSimulator", "У"))
        self.pushButton_5.setText(_translate("KeyboardSimulator", "Н"))
        self.pushButton_6.setText(_translate("KeyboardSimulator", "Г"))
        self.pushButton_7.setText(_translate("KeyboardSimulator", "Е"))
        self.pushButton_8.setText(_translate("KeyboardSimulator", "Ш"))
        self.pushButton_9.setText(_translate("KeyboardSimulator", "Х"))
        self.pushButton_10.setText(_translate("KeyboardSimulator", "З"))
        self.pushButton_11.setText(_translate("KeyboardSimulator", "Щ"))
        self.pushButton_12.setText(_translate("KeyboardSimulator", "Ъ"))
        self.pushButton_14.setText(_translate("KeyboardSimulator", "Ж"))
        self.pushButton_15.setText(_translate("KeyboardSimulator", "Ы"))
        self.pushButton_16.setText(_translate("KeyboardSimulator", "В"))
        self.pushButton_17.setText(_translate("KeyboardSimulator", "О"))
        self.pushButton_18.setText(_translate("KeyboardSimulator", "Р"))
        self.pushButton_19.setText(_translate("KeyboardSimulator", "Д"))
        self.pushButton_20.setText(_translate("KeyboardSimulator", "П"))
        self.pushButton_21.setText(_translate("KeyboardSimulator", "Э"))
        self.pushButton_22.setText(_translate("KeyboardSimulator", "Л"))
        self.pushButton_23.setText(_translate("KeyboardSimulator", "Ф"))
        self.pushButton_24.setText(_translate("KeyboardSimulator", "А"))
        self.pushButton_25.setText(_translate("KeyboardSimulator", "Ь"))
        self.pushButton_27.setText(_translate("KeyboardSimulator", "Ч"))
        self.pushButton_28.setText(_translate("KeyboardSimulator", "Ю"))
        self.pushButton_29.setText(_translate("KeyboardSimulator", "."))
        self.pushButton_30.setText(_translate("KeyboardSimulator", "Б"))
        self.pushButton_31.setText(_translate("KeyboardSimulator", "Т"))
        self.pushButton_32.setText(_translate("KeyboardSimulator", "С"))
        self.pushButton_33.setText(_translate("KeyboardSimulator", "И"))
        self.pushButton_34.setText(_translate("KeyboardSimulator", "Я"))
        self.pushButton_35.setText(_translate("KeyboardSimulator", "М"))
        self.pushButton_13.setText(_translate("KeyboardSimulator", "\\"))
        self.pushButton_37.setText(_translate("KeyboardSimulator", "ENTER"))
        self.pushButton_38.setText(_translate("KeyboardSimulator", "SHIFT"))
        self.pushButton_39.setText(_translate("KeyboardSimulator", "CAPS"))
        self.pushButton_40.setText(_translate("KeyboardSimulator", "TAB"))
        self.pushButton_26.setText(_translate("KeyboardSimulator", "0"))
        self.pushButton_41.setText(_translate("KeyboardSimulator", "2"))
        self.pushButton_42.setText(_translate("KeyboardSimulator", "3"))
        self.pushButton_43.setText(_translate("KeyboardSimulator", "7"))
        self.pushButton_44.setText(_translate("KeyboardSimulator", "6"))
        self.pushButton_45.setText(_translate("KeyboardSimulator", "9"))
        self.pushButton_46.setText(_translate("KeyboardSimulator", "5"))
        self.pushButton_47.setText(_translate("KeyboardSimulator", "8"))
        self.pushButton_48.setText(_translate("KeyboardSimulator", "1"))
        self.pushButton_49.setText(_translate("KeyboardSimulator", "4"))
        self.pushButton_50.setText(_translate("KeyboardSimulator", "-"))
        self.pushButton_51.setText(_translate("KeyboardSimulator", "="))
        self.pushButton_52.setText(_translate("KeyboardSimulator", "Ё"))
        self.pushButton_53.setText(_translate("KeyboardSimulator", "←"))
        self.pushButton_55.setText(_translate("KeyboardSimulator", "SHIFT"))
        self.label.setText(_translate("KeyboardSimulator", "Прогресс:"))
        self.label_2.setText(_translate("KeyboardSimulator", "Знаки:"))
        self.label_3.setText(_translate("KeyboardSimulator", "Слов в минуту:"))
        self.label_4.setText(_translate("KeyboardSimulator", "Ошибки:"))
        self.label_5.setText(_translate("KeyboardSimulator", "Точность:"))
        self.label_6.setText(_translate("KeyboardSimulator", "Время:"))
        self.label_7.setText(_translate("KeyboardSimulator", "100%"))
        self.label_8.setText(_translate("KeyboardSimulator", "0:00"))
        self.label_9.setText(_translate("KeyboardSimulator", "0"))
        self.label_10.setText(_translate("KeyboardSimulator", "0"))
        self.label_11.setText(_translate("KeyboardSimulator", "0"))
